models.py
from app import db
from datetime import datetime
import re
from flask_security import UserMixin, RoleMixin


def slugify(string):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', string).lower()


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '{}'.format(self.name)


roles_users = db.Table('roles_users',
                       db.Column('user_id',
                                 db.Integer(),
                                 db.ForeignKey('user.id')),
                       db.Column('role_id',
                                 db.Integer(),
                                 db.ForeignKey('role.id'))
                       )


class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
	title = StringField("Заговолок статьи")
	body = TextAreaField("Текст")

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

from models import *
from admin import *


admin = Admin(app, "Главная", url="/", index_view=HomeAdminView(name="Admin Panel"))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view((TagAdminView(Tag, db.session)))
admin.add_view((ModelView(Role, db.session)))

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db
from posts.blueprint import posts
import view


app.register_blueprint(posts, url_prefix='/blog')


if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from models import Post, Tag
from .forms import PostForm
from app import db
import datetime
from flask_security import login_required


posts = Blueprint('posts', __name__, template_folder='templates')

MONTHS = {'01': 'Январь',
		  '02': 'Февраль',
		  '03': 'Март',
		  '04': 'Апрель',
		  '05': 'Май',
		  '06': 'Июнь',
		  '07': 'Июль',
		  '08': 'Август',
		  '09': 'Сентябрь',
		  '10': 'Октябрь',
		  '11': 'Ноябрь',
		  '12': 'Декабрь'}

START_YEAR = 2020


def get_date():
	cur_date = str(datetime.datetime.now())[:7].split('-')
	cur_month = cur_date[1]
	cur_year = int(cur_date[0])
	current_date = f'{cur_year}-{cur_month}'

	return cur_year, cur_month, current_date


def list_archive(cur_year, cur_month, current_date):

	posts = Post.query

	result_archive = []

	while START_YEAR <= cur_year:

		for month in sorted(MONTHS.keys(), reverse=True):
			date_string = f'{cur_year}-{month}'
			if date_string != current_date:
				if posts.filter(Post.created.contains(date_string)).all():
					result_archive.append((str(cur_year), month, MONTHS[month]))

		cur_year -= 1

	return result_archive


@posts.route('/create', methods=["POST", "GET"])
@login_required
def create_post():
	if request.method == "POST":
		title = request.form['title']
		body = request.form['body']
		try:
			post = Post(title=title, body=body)
			db.session.add(post)
			db.session.commit()
		except:
			print("Не получилось записать новый пост в базу данных")
		return redirect(url_for('posts.index'))

	form = PostForm()
	return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
	post = Post.query.filter(Post.slug == slug).first_or_404()

	if request.method == 'POST':
		form = PostForm(formdata=request.form, obj=post)
		form.populate_obj(post)
		db.session.commit()

		return redirect(url_for('posts.post_detail', slug=post.slug))

	form = PostForm(obj=post)
	return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/posts/<slug>/delete')
@login_required
def delete_post(slug):
	post = Post.query.filter(Post.slug == slug).first_or_404()
	try:
		db.session.delete(post)
		db.session.commit()
	except:
		print("Не получилось удалить пост из базы данных")
	return redirect(url_for('posts.index'))


@posts.route('/')
def index():

	cur_year, cur_month, current_date = get_date()

	s = request.args.get('s')
	if s:
		posts = Post.query.filter(Post.title.contains(s) | Post.body.contains(s)).all()
	else:
		posts = Post.query.filter(Post.created.contains(current_date)).all()[::-1]

	tags_all = Tag.query.all()
	return render_template('posts/index.html',
						   posts=posts,
						   tags_all=tags_all,
						   result_archive=list_archive(cur_year, cur_month, current_date))


#@posts.route('')

@posts.route('/<slug>')
def post_detail(slug):
	post = Post.query.filter(Post.slug==slug).first_or_404()
	tags = post.tags
	result_archive = list_archive(*get_date())
	try:
		post_pre = Post.query.filter(Post.id == post.id - 1).first()
	except:
		post_pre = None
	try:
		post_next = Post.query.filter(Post.id == post.id + 1).first()
	except:
		post_next = None
	posts = Post.query.all()[::-1][:4]
	tags_all = Tag.query.all()
	return render_template('posts/post_detail.html',
						    post=post,
						    post_pre=post_pre,
						    post_next=post_next,
						    posts=posts,
						    tags=tags,
						    tags_all=tags_all,
						   result_archive=result_archive)


@posts.route('/tag/<slug>')
def tag_detail(slug):
	tag = Tag.query.filter(Tag.slug==slug).first_or_404()
	posts = tag.posts.all()
	posts_recent = Post.query.all()[::-1][:4]
	tags_all = Tag.query.all()
	result_archive = list_archive(*get_date())
	return render_template('posts/tag_detail.html', tag=tag, posts=posts,
						   posts_recent=posts_recent, tags_all=tags_all,
						   result_archive=result_archive)


@posts.route('/<year>/<month>')
def archive_detail(year, month):
	last_date = f'{year}-{month}'
	archive_posts = Post.query.filter(Post.created.contains(last_date)).order_by(Post.created.desc()).all()
	tags_all = Tag.query.all()
	result_archive = list_archive(*get_date())
	recent_posts = Post.query.all()[::-1][:4]

	return render_template('posts/archive_detail.html',
						   archive_posts=archive_posts,
						   month_name=MONTHS[month],
						   year=year,
						   tags_all=tags_all,
						   result_archive=result_archive,
						   recent_posts=recent_posts)

posts/templates/posts/archive_detail.html
{% extends 'base.html' %}

{% block title %}
	Архив за {{ month_name }} {{ year }}
{% endblock %}

{% block body_href %}
<body class="archive category wp-custom-logo hfeed">
{%  endblock %}

{% block content %}
<section class="page-header-section" style="background-image: url(
	https://www.graphiclibrary.com/craft-blog/wp-content/themes/craftblog/asset/img/blog-1.jpg);">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<div class="paget-title">
				  <h2>
				     {{ month_name }} {{ year }}
				 </h2>
				</div>
			</div>
		</div>
	</div>
</section>

	<div id="primary" class="content-area">
		<main id="main" class="site-main">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-7 col-md-8">
                        <header class="page-header">
                            <h1 class="page-title">Архив: {{ month_name }} {{ year }}</h1>
                        </header><!-- .page-header -->
{% for post in archive_posts %}
<article id="post-{{ post.id }}" class="single-blog-item post-{{ post.id }} post type-post status-publish format-standard has-post-thumbnail hentry">
	<header class="entry-header">
		{% for tag in post.tags %}
		<h4 class="categories">
			<a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}">
			{{ tag.name }}
		</a>
	 	</h4>
		{% endfor %}
	<h1 class="entry-title">
	{{ post.title }}
    </h1>
		<div class="entry-meta">
				<span class="posted-on">Posted on
					<a href="https://www.graphiclibrary.com/craft-blog/cute-and-fluffy/" rel="bookmark">
						<time class="entry-date published" datetime="2019-03-28T16:29:11+00:00"> {{ post.created.date() }}
						</time>
						<time class="updated" datetime="2019-03-28T16:37:56+00:00">
						{{ post.created.date() }}
					</time>
				</a>
			</span>
					</div><!-- .entry-meta -->
			</header><!-- .entry-header -->


			<div class="post-thumbnail">
				<img width="1152" height="559" src="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg 1152w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-300x146.jpg 300w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-768x373.jpg 768w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-1024x497.jpg 1024w" sizes="(max-width: 1152px) 100vw, 1152px" />
			</div><!-- .post-thumbnail -->


	<div class="entry-content">
        <div class="excerpt">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">Читать полностью</a>
        </div>
    </div><!-- .entry-content -->

</article><!-- #post-46 -->
{% endfor %}
                    </div>
{% endblock %}

{% block aside_recent %}
{% for post in recent_posts %}
    <li>
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
            {{ post.title }}
        </a>
    </li>
{% endfor %}
{% endblock %}

{% block aside_archive %}
    {% for year, month, month_name in result_archive %}
        <li>
            <a href="{{ url_for('posts.archive_detail', year=year, month=month) }}">{{ month_name }} {{ year }}</a>
        </li>
    {% endfor %}
{% endblock %}

{% block aside_tags %}
    {% for tag in tags_all %}
    <li class="cat-item cat-item-{{ tag.id }}">
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a>
    </li>
    {% endfor %}
{% endblock %}

{% block div %}
</div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
	Blog Yulia Hand Made
{% endblock %}


{%block content_title %}
	Blueprint (will be changed)
{% endblock %}

{% block body_href %}
    <body class="home blog wp-custom-logo hfeed">
{% endblock %}

{% block content_for_index %}
            <div id="primary" class="content-area">
                <main id="main" class="site-main">
			        <div class="container">
				        <div class="row justify-content-between">
{% endblock %}
{% block content %}
					<div class="col-lg-7 col-md-8">
						{% for post in posts %}
						<article id="post-{{ post.id }}" class="single-blog-item post-{{ post.id }} post type-post status-publish format-standard has-post-thumbnail hentry category-kids-crafts">
							<header class="entry-header">
                                {% for tag in post.tags %}
								<h4 class="categories">
									<a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a>
								</h4>
                                {% endfor %}
								<h2 class="entry-title">
									<a href="{{ url_for('posts.post_detail', slug=post.slug) }}" rel="bookmark"> {{ post.title }} </a>
								</h2>
								<div class="entry-meta">
									<span class="posted-on">
										Опубликовано
										<a href="{{ url_for('posts.post_detail', slug=post.slug) }}" rel="bookmark">
											<time class="entry-date published" datetime="2019-03-28T16:29:11+00:00"> {{ post.created.date() }}
											</time>
											<time class="updated" datetime="2019-03-28T16:37:56+00:00"> {{ post.created.date() }} </time>
										</a>
									</span>
								</div><!-- .entry-meta -->
							</header><!-- .entry-header -->


							<a class="post-thumbnail" href="{{ url_for('posts.post_detail', slug=post.slug) }}" aria-hidden="true" tabindex="-1">
								<img width="1152" height="559" src="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Cute And Fluffy" srcset="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg 1152w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-300x146.jpg 300w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-768x373.jpg 768w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-1024x497.jpg 1024w" sizes="(max-width: 1152px) 100vw, 1152px" />
							</a>


							<div class="entry-content">
								<div class="excerpt">
									<a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
										Читать полностью
									</a>
								</div>
							</div><!-- .entry-content -->

						</article><!-- #post-46 -->
                        {% endfor %}
					</div>
{% endblock %}
{% block aside_recent %}
{% for post in posts[:4] %}
    <li>
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
            {{ post.title }}
        </a>
    </li>
{% endfor %}
{% endblock %}

{% block aside_archive %}
    {% for year, month, month_name in result_archive %}
        <li>
            <a href="{{ url_for('posts.archive_detail', year=year, month=month) }}">{{ month_name }} {{ year }}</a>
        </li>
    {% endfor %}
{% endblock %}

{% block aside_tags %}
    {% for tag in tags_all %}
    <li class="cat-item cat-item-{{ tag.id }}">
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a>
    </li>
    {% endfor %}
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
	{{ post.title }}
{% endblock %}

{% block body_href %}
<body class="post-template-default single single-post postid-{{ post.id }} single-format-standard wp-custom-logo">
{%  endblock %}

{% block content %}
<section class="page-header-section" style="background-image: url(
	https://www.graphiclibrary.com/craft-blog/wp-content/themes/craftblog/asset/img/blog-1.jpg);">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<div class="paget-title">
				  <h2>
				     {{ post.title }}
				 </h2>
				</div>
			</div>
		</div>
	</div>
</section>

	<div id="primary" class="content-area">
		<main id="main" class="site-main">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-7 col-md-8">

<article id="post-{{ post.id }}" class="single-blog-item post-{{ post.id }} post type-post status-publish format-standard has-post-thumbnail hentry category-kids-crafts">
	<header class="entry-header">
		{% for tag in tags %}
		<h4 class="categories">
			<a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}">
			{{ tag.name }}
		</a>
	 	</h4>
		{% endfor %}
	<h1 class="entry-title">
	{{ post.title }}
    </h1>
		<div class="entry-meta">
				<span class="posted-on">Posted on
					<a href="https://www.graphiclibrary.com/craft-blog/cute-and-fluffy/" rel="bookmark">
						<time class="entry-date published" datetime="2019-03-28T16:29:11+00:00"> {{ post.created.date() }}
						</time>
						<time class="updated" datetime="2019-03-28T16:37:56+00:00">
						{{ post.created.date() }}
					</time>
				</a>
			</span>
					</div><!-- .entry-meta -->
			</header><!-- .entry-header -->


			<div class="post-thumbnail">
				<img width="1152" height="559" src="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg 1152w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-300x146.jpg 300w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-768x373.jpg 768w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-1024x497.jpg 1024w" sizes="(max-width: 1152px) 100vw, 1152px" />
			</div><!-- .post-thumbnail -->


	<div class="entry-content">
		<p>
			{{ post.body }}
		</p>
    </div><!-- .entry-content -->

</article><!-- #post-46 -->
<nav class="navigation post-navigation" role="navigation">
	<h2 class="screen-reader-text">
		Post navigation
	</h2>
	<div class="nav-links">
            {% if post_pre %}
            <div class="nav-previous">
                <a href="{{ url_for('posts.post_detail', slug=post_pre.slug) }}" rel="prev">
                    {{ post_pre.title }}
                </a>
            </div>
            {% endif %}
            {% if post_next %}
            <div class="nav-next">
                <a href="{{ url_for('posts.post_detail', slug=post_next.slug) }}" rel="next">
                    {{ post_next.title }}
                </a>
            </div>
            {% endif %}
        </div>

	</nav>

<div id="comments" class="comments-area">
<!--
		<div id="respond" class="comment-respond">
		<h3 id="reply-title" class="comment-reply-title">Leave a Reply <small><a rel="nofollow" id="cancel-comment-reply-link" href="/craft-blog/cute-and-fluffy/#respond" style="display:none;">Cancel reply</a></small></h3>			<form action="https://www.graphiclibrary.com/craft-blog/wp-comments-post.php" method="post" id="commentform" class="comment-form" novalidate>
				<p class="comment-notes"><span id="email-notes">Your email address will not be published.</span> Required fields are marked <span class="required">*</span></p><p class="comment-form-comment"><label for="comment">Comment</label> <textarea id="comment" name="comment" cols="45" rows="8" maxlength="65525" required="required"></textarea></p><p class="comment-form-author"><label for="author">Name <span class="required">*</span></label> <input id="author" name="author" type="text" value="" size="30" maxlength="245" required='required' /></p>
<p class="comment-form-email"><label for="email">Email <span class="required">*</span></label> <input id="email" name="email" type="email" value="" size="30" maxlength="100" aria-describedby="email-notes" required='required' /></p>
<p class="comment-form-url"><label for="url">Website</label> <input id="url" name="url" type="url" value="" size="30" maxlength="200" /></p>
<p class="comment-form-cookies-consent"><input id="wp-comment-cookies-consent" name="wp-comment-cookies-consent" type="checkbox" value="yes" /><label for="wp-comment-cookies-consent">Save my name, email, and website in this browser for the next time I comment.</label></p>
<p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="Post Comment" /> <input type='hidden' name='comment_post_ID' value='46' id='comment_post_ID' />
<input type='hidden' name='comment_parent' id='comment_parent' value='0' />
</p>			</form>
			</div><!-- #respond -->

</div><!-- #comments -->

					</div>

{% endblock %}
{% block aside_recent %}
{% for post in posts %}
    <li>
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
            {{ post.title }}
        </a>
    </li>
{% endfor %}
{% endblock %}

{% block aside_archive %}
    {% for year, month, month_name in result_archive %}
        <li>
            <a href="{{ url_for('posts.archive_detail', year=year, month=month) }}">{{ month_name }} {{ year }}</a>
        </li>
    {% endfor %}
{% endblock %}

{% block aside_tags %}
    {% for tag in tags_all %}
    <li class="cat-item cat-item-{{ tag.id }}">
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a>
    </li>
    {% endfor %}
{% endblock %}
    {% block template_edit_add %}
        <li>
            <a href="{{ url_for('posts.edit_post', slug=post.slug) }}" >Редактировать эту публикацию</a>
        </li>
        <li>
            <a href="{{ url_for('posts.delete_post', slug=post.slug) }}" >Удалить эту публикацию</a>
        </li>
    {% endblock %}
{% block div %}
</div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
	{{ tag.name }}
{% endblock %}

{% block body_href %}
<body class="archive category category-{{ tag.name }} category-{{ tag.id }} wp-custom-logo hfeed">
{%  endblock %}

{% block content %}
<section class="page-header-section" style="background-image: url(
	https://www.graphiclibrary.com/craft-blog/wp-content/themes/craftblog/asset/img/blog-1.jpg);">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center">
				<div class="paget-title">
				  <h2>
				     {{ tag.name }}
				 </h2>
				</div>
			</div>
		</div>
	</div>
</section>

	<div id="primary" class="content-area">
		<main id="main" class="site-main">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-7 col-md-8">
                        <header class="page-header">
                            <h1 class="page-title">Категория: {{ tag.name }}</h1>
                        </header><!-- .page-header -->
{% for post in posts %}
<article id="post-{{ post.id }}" class="single-blog-item post-{{ post.id }} post type-post status-publish format-standard has-post-thumbnail hentry category-{{ tag.name }}">
	<header class="entry-header">
		{% for tag in tags %}
		<h4 class="categories">
			<a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}">
			{{ tag.name }}
		</a>
	 	</h4>
		{% endfor %}
	<h1 class="entry-title">
	{{ post.title }}
    </h1>
		<div class="entry-meta">
				<span class="posted-on">Posted on
					<a href="https://www.graphiclibrary.com/craft-blog/cute-and-fluffy/" rel="bookmark">
						<time class="entry-date published" datetime="2019-03-28T16:29:11+00:00"> {{ post.created }}
						</time>
						<time class="updated" datetime="2019-03-28T16:37:56+00:00">
						{{ post.created }}
					</time>
				</a>
			</span>
					</div><!-- .entry-meta -->
			</header><!-- .entry-header -->


			<div class="post-thumbnail">
				<img width="1152" height="559" src="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" srcset="https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy.jpg 1152w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-300x146.jpg 300w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-768x373.jpg 768w, https://www.graphiclibrary.com/craft-blog/wp-content/uploads/2019/03/fluffy-1024x497.jpg 1024w" sizes="(max-width: 1152px) 100vw, 1152px" />
			</div><!-- .post-thumbnail -->


	<div class="entry-content">
        <div class="excerpt">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">Читать полностью</a>
        </div>
    </div><!-- .entry-content -->

</article><!-- #post-46 -->
{% endfor %}
                    </div>
{% endblock %}

{% block aside_recent %}
{% for post in posts_recent %}
    <li>
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
            {{ post.title }}
        </a>
    </li>
{% endfor %}
{% endblock %}

{% block aside_archive %}
    {% for year, month, month_name in result_archive %}
        <li>
            <a href="{{ url_for('posts.archive_detail', year=year, month=month) }}">{{ month_name }} {{ year }}</a>
        </li>
    {% endfor %}
{% endblock %}

{% block aside_tags %}
    {% for tag in tags_all %}
    <li class="cat-item cat-item-{{ tag.id }}">
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a>
    </li>
    {% endfor %}
{% endblock %}

{% block div %}
</div>
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
        <h3 class="comment-reply-title {{ category }}">{{ message }}</h3>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}